global:
  default_meta: inline

fields:
  tags:
    default_meta: frontmatter
    frontmatter_separators: [" ", ","]
    inline_separators: [" "]
  tag:
    default_meta: frontmatter
    frontmatter_separators: [" ", ","]
    inline_separators: [" "]
